// 用于 patch 的 long_intro 内容（HTML 多段，不 escape，由 buildHubs 直接注入）
// 每段为编辑性原创评论，包含：源流 / 文化位置 / 西方读者入门指引 / 推荐阅读顺序
// 语调参照 Penguin Classics / NYRB 导言风格：知性、克制、不画饼

module.exports = {
  'fox-spirits': `
<p>The Chinese fox spirit — the <em>huli jing</em> 狐狸精 — has no clean Western equivalent. She is not a vampire, not a succubus, not a witch. Across more than a thousand years, she shifts shape: a Tang-dynasty merchant's mistress in Shen Jiji's <em>Biography of Lady Ren</em> (任氏传, c. 781), the loyal scholar-wife of countless Qing tales, the apprentice on a slow road to immortality, the cunning trickster who repays kindness with kindness and cruelty with ruin. To read these stories well is to give up the single image and accept the spectrum.</p>
<p>The classical sources gather mostly in three places. The Tang <em>chuanqi</em> 传奇 tradition gave the fox literary dignity. Pu Songling (蒲松龄, 1640–1715) made her the central figure of <em>Strange Tales from a Chinese Studio</em> (聊斋志异), where nearly a hundred fox tales explore desire, fidelity, and the strange ethics of crossing species. Ji Yun (纪昀, 1724–1805), the more skeptical bureaucrat, recorded her in <em>Notes from the Yuewei Hermitage</em> (阅微草堂笔记) as a creature one might reasonably argue with at midnight.</p>
<p>For new readers, a useful entry point is one of the warmer Pu Songling tales — a fox who marries a poor scholar, raises his children, and quietly leaves when the household no longer needs her. From there, move outward: a Ji Yun fragment for the dry rationalist tone, a Tang piece for the older, stranger formality. Read them as character studies first, folklore second. The fox is rarely the moral of her own story; she is the lens through which the human is examined.</p>`,

  'love-across-death': `
<p>In the classical Chinese imagination, death is rarely the end of a love story — it is, more often, the test. The dead return to keep promises. The living descend to the underworld to argue for a soul. Husbands and wives meet in dreams, in inns, on the edges of unfamiliar mountains, and resume the conversation that mortality interrupted. Western readers who arrive expecting Gothic romance — the haunted house, the cursed lover — will find the temperature here different. The grief is real, but the metaphysics is administrative: spirits travel, courts intervene, vows are honored or denied on the record.</p>
<p>The tradition runs deep. The <em>Records of the Strange</em> (搜神记) of the fourth century already collects ghost-bride tales. The Tang <em>chuanqi</em> elevated the form into psychological fiction. By the Ming and Qing, drama (<em>The Peony Pavilion</em> 牡丹亭, <em>The Palace of Eternal Life</em> 长生殿) and short fiction (Pu Songling's <em>Liaozhai</em>, Yuan Mei's <em>Zibuyu</em> 子不语) had pushed the question further: if love can summon the dead, what does it owe the living?</p>
<p>A reasonable reading order is to begin with one famous tale — Nie Xiaoqian 聂小倩, the ghost rescued from servitude by a scholar's restraint — to establish the moral grammar. Then move to lesser-known stories: the merchant's wife who returns only to settle accounts, the betrothed who wait through a generation. The genre is less interested in the supernatural than in fidelity, and the ghosts know it.</p>`,

  'karma-and-retribution': `
<p>Chinese karma is not the karma of Indian Buddhism, though it descends from it. By the time Buddhist doctrine had filtered through several centuries of Chinese folk imagination, <em>yinguo</em> 因果 — cause and effect — had become something more local: a moral ledger kept with the patience of a Chinese county clerk. Debts accrue interest. Animals remember the human who once mistreated them. Strangers recognize one another from a previous life. The arithmetic is exact, sometimes terrifyingly so, and rarely in a hurry.</p>
<p>The earliest collections — the Tang <em>Records of the Underworld</em> (冥报记) of Tang Lin — are openly didactic, written to convince readers of a Buddhist moral order. By the Qing, in Ji Yun's hands, the genre had cooled into something closer to forensic anecdote: he records the case, names his source, and lets the reader weigh the evidence. Yuan Mei's <em>Zibuyu</em> tilts more skeptical still, and Pu Songling's tales sit in the literary middle, willing to use karma as a structural device for tragedy.</p>
<p>For first-time readers, the short retribution tale — a single act of cruelty and its delayed return — is the cleanest entry. From there, the harder pieces: stories of debts paid across lifetimes, of animals who recognize old enemies in human form, of the slow patience that does not look like justice until much later. Read them not as religious instruction but as a long, sober argument about consequence.</p>`,

  'afterlife-and-underworld': `
<p>The Chinese underworld is not <em>hell</em> in the Western sense, and translating it that way usually misleads. <em>Diyu</em> 地狱 is a transit system: souls arrive, are processed, judged, sometimes punished, often reassigned. King Yama (阎罗王) presides, but the real work is done by clerks. Magistrates examine paperwork. Ghost officials chase down the dead who arrived before their time. Reincarnation has a queue, and the queue has a manager. Anyone who has spent an afternoon in a Chinese government office will find the architecture familiar.</p>
<p>The literary roots reach back to the <em>Record of Ghosts and Marvels</em> (幽明录, fifth century) and the Tang <em>Records of Underworld Auspice</em> (冥祥记). By the Ming and Qing, full underworld bureaucracies had been mapped — the Ten Courts, the Bridge of Helplessness, the Terrace of the Mirror that shows a soul its sins. The fiction of Pu Songling, Ji Yun, and Yuan Mei treats this geography as essentially settled, then asks more interesting questions: what if the magistrate is wrong, what if a clerk takes a bribe, what if a soul argues its case well.</p>
<p>A useful first reading is a "soul travel" tale — a man taken below by mistake, examined, and returned with a clearer view of his life. From there, the courtroom stories: petitioners arguing for justice the upper world failed to deliver. The hub rewards readers who notice that the underworld here is, above all, a critique of the world above it.</p>`,

  'hauntings': `
<p>Not every Chinese ghost wants vengeance. Many simply want a candle, a conversation, a meal at the right time of year, or to be left in peace. The hauntings tradition in classical China is wider and gentler than the English word <em>haunting</em> usually suggests. A traveler shares a temple with a quiet stranger and only at dawn realizes the stranger had no shadow. A scholar reads through the night while something watches from the rafters and, in time, asks a question. The encounter is more often unsettling than terrifying, and the etiquette of how to behave during it is taken seriously.</p>
<p>The genre is enormous. The <em>Records of the Strange</em> (搜神记) of Gan Bao opens it formally in the fourth century. The Tang <em>Records of Vast Marvels</em> (广异记) extends it. By the Qing it has split into temperaments: Ji Yun's cool reportage in the <em>Yuewei Hermitage Notes</em>, Yuan Mei's appetite for the absurd in <em>Zibuyu</em>, Pu Songling's literary depth in <em>Liaozhai</em>. Across all of them, the ghost is rarely the point. The point is the human: how a scholar, a soldier, a widow, a child responds when the boundary between worlds becomes thin.</p>
<p>For new readers, begin with the lighter encounters — a fearless scholar who refuses to be frightened, a widow who learns to live above a haunted floor — and work toward the philosophical pieces, where the ghost asks something the living person cannot easily answer. The literature here is, finally, about composure: how to share a country with the dead without losing one's nerve or one's manners.</p>`,

  'taoist-marvels': `
<p>Long before <em>xianxia</em> 仙侠 became a publishing category, classical China had a thousand years of Taoist marvels: hermits who walked through walls, alchemists who paid for immortality in years off their own lives, swordsmen who flew their blades across a province on a single breath. The literature is older and quieter than its modern descendants. It rewards patience.</p>
<p>The early sources are unembarrassedly hagiographic — Ge Hong's <em>Biographies of Divine Immortals</em> (神仙传, fourth century), the Tang <em>Gleanings of Immortal Lore</em> (仙传拾遗) — written to record the lives of those who, the compilers believed, had succeeded. By the Song the Daoist canon (<em>Yunji Qiqian</em> 云笈七签) had absorbed and systematized the material; by the Ming and Qing, it had loosened into the entertaining miscellanies of Pu Songling, Ji Yun, and Yuan Mei, where Daoist masters appear as characters whose powers are real but whose patience is being tested.</p>
<p>What unites the tradition is its economic seriousness. Power has a price. Years of meditation, decades of failed elixirs, the abandonment of family — the texts rarely let the cost slide out of view. For Western readers, the most useful frame is not <em>magic</em> but <em>apprenticeship</em>: a long, often disappointing, sometimes transcendent training in what the Chinese tradition calls the Way (<em>Dao</em> 道). A reasonable first reading is a short master-and-disciple tale, where the student learns one small thing and recognizes how much remains. From there, the longer transformations — and the rarer accounts of those who paid the price and decided, in the end, that immortality was not what they wanted.</p>`,
};
